from typing import Set
from src.Node import Node, NodeType
import os
import json

def find_all_json_files(root_dir: str) -> list[str]:
    json_files = []
    for current_folder, sub_folder, files in os.walk(root_dir):
        for file in files:
            if file.endswith('.json'):
                path = os.path.join(current_folder, file)
                json_files.append(path)
    return json_files

def load_exec_pins_from_json_files(json_files: list[str]) -> set[str]:
    exec_pins = set()
    for json_file in json_files:
        with open(json_file, 'r') as f:
            data = json.load(f)
            if 'exec' in data:
                exec_pins.update(data['exec'])
    return exec_pins

class ExecEdge:
    def __init__(self, from_node, to_node, exec_pin="default"):
        self.from_node = from_node
        self.to_node = to_node
        self.exec_pin = exec_pin

    def __str__(self):
        return f"({self.from_node}, {self.to_node}, {self.exec_pin})"

class DataEdge:
    def __init__(self, from_node, to_node, output_name, input_name):
        self.from_node = from_node
        self.to_node = to_node
        self.output_name = output_name
        self.input_name = input_name

    def __str__(self):
        return f"({self.from_node}, {self.to_node}, {self.output_name}, {self.input_name})"

class Block:
    def __init__(self, parent_node: Node) -> None:
        if parent_node is None or parent_node.type != NodeType.EVENT:
            raise ValueError("Parent node must be EVENT node")
        self.parent_node = parent_node
        self.exec_edges = []
        self.data_edges = []
        self.all_custom_exec_output = []
        self._load_custom_exec_output()
        self.events_counts = parent_node.events_count

    def _load_custom_exec_output(self):
        root_dir = "nodes"
        files = find_all_json_files(root_dir)
        execs_found = load_exec_pins_from_json_files(files)
        for e in execs_found:
            if e != "Continue":
                self.all_custom_exec_output.append(e)

    def connect_exec(self, from_node, to_node, exec_pin="default") -> None:
        self.exec_edges.append(ExecEdge(from_node, to_node, exec_pin))

    def connect_data(self, from_node, to_node, output_name, input_name) -> None:
        self.data_edges.append(DataEdge(from_node, to_node, output_name, input_name))

    def compute_node(self, node: Node) -> str:
        """
        Compute node dependencies and generate code for FUNCTION nodes
        Returns any code generated by FUNCTION nodes in the dependency chain
        """
        dependency_code = ""
        for edge in self.data_edges:
            if edge.to_node == node:
                # Recursively compute dependencies
                dep_code = self.compute_node(edge.from_node)
                dependency_code += dep_code
                
                # Generate code for the dependency node
                from_node_code = edge.from_node.toLuau()
                if from_node_code and edge.from_node.type == NodeType.FUNCTION:
                    # FUNCTION nodes generate code that needs to be included
                    dependency_code += from_node_code + "\n"
                
                # Get the output value and set it as input
                value = edge.from_node.getOutputValue(edge.output_name)
                if value is not None:
                    node.setInputValue(edge.input_name, value)
        
        return dependency_code

    def _run_node(self, node: Node, indent: int = 0, executed: Set[Node] = None) -> str:
        if executed is None:
            executed = set()

        print(f"[DEBUG] _run_node called for: {node.title} (type: {node.type})")

        if node in executed and node.type != NodeType.EVENT:
            print(f"[DEBUG] Node {node.title} already executed, skipping")
            return ""

        # Compute dependencies and get any code from FUNCTION nodes
        dependency_code = self.compute_node(node)
        print(f"[DEBUG] Dependency code for {node.title}: {len(dependency_code)} chars")
        executed.add(node)

        code = ""
        
        # Add dependency code (from FUNCTION nodes) with proper indentation
        if dependency_code:
            for line in dependency_code.strip().split("\n"):
                if line.strip():
                    code += "    " * indent + line + "\n"
        
        # Generate code for current node
        node_code = node.toLuau()
        print(f"[DEBUG] Node {node.title} toLuau() returned: {repr(node_code)}")
        if node_code:
            code += "    " * indent + node_code + "\n"

        edges_from_node = [e for e in self.exec_edges if e.from_node == node]
        print(f"[DEBUG] Node {node.title} has {len(edges_from_node)} exec edges")

        then_executed = False
        structured_branch_executed = False

        for e in edges_from_node:
            if e.exec_pin in self.all_custom_exec_output and e.exec_pin != "Else":
                next_indent = indent + 1
                code += self._run_node(e.to_node, next_indent, executed)
                if e.exec_pin == "Then":
                    then_executed = True
                structured_branch_executed = True

        if then_executed:
            else_edge = next((e for e in edges_from_node if e.exec_pin == "Else"), None)
            if else_edge:
                code += "    " * indent + "else\n"
                code += self._run_node(else_edge.to_node, indent + 1, executed)

        continue_edge = None
        default_edges = []
        handled_pins = set(self.all_custom_exec_output)

        for e in edges_from_node:
            if e.exec_pin not in handled_pins:
                if e.exec_pin == "Continue":
                    continue_edge = e
                else:
                    default_edges.append(e)

        if structured_branch_executed:
            code += "    " * indent + "end\n"

        if continue_edge:
            code += self._run_node(continue_edge.to_node, indent, executed)

        for e in default_edges:
            code += self._run_node(e.to_node, indent, executed)

        return code

    def __str__(self):
        print("-" * 50)
        for n in self.exec_edges:
            print("- Exec Edge: ", n)
        for n in self.data_edges:
            print("- Data Edge: ", n)
        print("-" * 50)
        return ""

    def run(self) -> str:
        code = self._run_node(self.parent_node)
        is_custom_event_start = self.parent_node.type == NodeType.EVENT and self.parent_node.title != "Start"
        if is_custom_event_start:
            code += "end)\n" * self.events_counts
        return code
